### ISSUE TITLE
Additional info around the error "JRELoadError"

### ISSUE THREAD

**Issue by robolmos** [kkevinm/iTunes-Discord-RP#43]
Thanks for building this app. Additional info on the issue if desired to work around in the future:

```
[~]$ /usr/libexec/java_home -V
Matching Java Virtual Machines (1):
    11.0.2, x86_64:	"OpenJDK 11.0.2"	/Library/Java/JavaVirtualMachines/openjdk-11.0.2.jdk/Contents/Home
```

```
[~]$ java -version
openjdk version "11.0.2" 2019-01-15
OpenJDK Runtime Environment 18.9 (build 11.0.2+9)
OpenJDK 64-Bit Server VM 18.9 (build 11.0.2+9, mixed mode)
```

```
[~]$ java -jar ~/Downloads/iTunesDiscordRP-1.5.7.jar
Oct 14, 2020 7:08:10 PM com.github.kevinmussi.itunesrp.Main main
INFO: Application started running.
Exception in thread "main" java.lang.NoClassDefFoundError: com/apple/eawt/AppEventListener
	at com.github.kevinmussi.itunesrp.Main.main(Main.java:66)
Caused by: java.lang.ClassNotFoundException: com.apple.eawt.AppEventListener
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:583)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	... 1 more
```

Seems that openjdk has removed the Mac-specific classes, causing the error, but looks like there's a new API to use: http://openjdk.java.net/jeps/272 -- says "Closed / Delivered" so might work?

I'm not sure if these classes are mandatory for the app, but an alternative could be a way to detect the lack of the Mac classes, show a warning, and fallback to running without Mac desktop features.

**Comment by kkevinm** [comment]
That's strange, as the com.apple.eawt package is just one the dependencies of the project (specified in the pom as "orange-extensions") so it should work on any jdk theoretically.

**Comment by robolmos** [comment]
I believe the orange-extensions is only a collection of updated stub classes, but would still need a JRE that provides the com.apple.eawt* functionality, which openjdk no longer does. 

I believe it was changed to the java.awt.desktop package with similar classes like AppReopenedListener. There's also java.awt.Taskbar.

**Comment by kkevinm** [comment]
Oh, you're right.
Also I'm aware of the new package, but for now I'll keep Java8 compatibility since the packaged .app relies on it to run. I guess a dirty solution would be to include the missing jar file in the classpath.

**Comment by carmparm** [comment]
Is this updated for: macOS 15.4.1? or do we still need the java patch?

Music version: 1.5.4.70
