### ISSUE TITLE
Dosent work... i dont know why....

### ISSUE THREAD

**Issue by TureBentzin** [kkevinm/iTunes-Discord-RP#62]
```
D:\MainDesktop\Place\Itunes ric>java -jar iTunesDiscordRP-1.5.7.jar
Juli 06, 2021 8:14:31 PM com.github.kevinmussi.itunesrp.Main main
INFO: Application started running.
Exception in thread "main" java.lang.reflect.InaccessibleObjectException: Unable to make field private static volatile java.nio.charset.Charset java.nio.charset.Charset.defaultCharset accessible: module java.base does not "opens java.nio.charset" to unnamed module @27fa135a
        at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:357)
        at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:297)
        at java.base/java.lang.reflect.Field.checkCanSetAccessible(Field.java:177)
        at java.base/java.lang.reflect.Field.setAccessible(Field.java:171)
        at com.github.kevinmussi.itunesrp.Main.main(Main.java:41)

D:\MainDesktop\Place\Itunes ric>PAUSE
Drücken Sie eine beliebige Taste . . .
```

**Comment by gilciaf** [comment]
Estou com o mesmo erro ao ler um certificado digital

**Comment by JamesBissick** [comment]
Use this instead https://github.com/NextFire/apple-music-discord-rpc
